wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1679940255.046211
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.10.6
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 5.0e-05
